version: "3.9"

services:
  master:
    image: mirzaeimahdi409/systems_analysis_design_master:latest
    ports:
      - target: 8080
        published: 8080
    deploy:
      replicas: 2
      mode: "replicated"
      restart_policy:
        condition: "on-failure"
      resources:
        limits:
          cpus: "0.8"
          memory: "900M"
        reservations:
          cpus: "0.2"
          memory: "250M"
